AdminMino/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('mycompany/', include('mycompany.urls')),
    path('customers/', include('customers.urls')),
    path('suppliers/', include('suppliers.urls')),
    path('costs/', include('costs.urls')),
    path('entries/', include('entries.urls')),
    path('support/', include('support.urls')),
    path('taxes/', include('taxes.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from main.views import HomeView


urlpatterns = [
    path('login', LoginView.as_view(template_name="main/login.html"), name="login"),
    path('logout', LogoutView.as_view(template_name="main/logout.html"), name="logout"),
    path('', HomeView.as_view(), name="home"),
]

suppliers/urls.py
from django.urls import path
from suppliers.views import (
    SupplierView,
    NewSupplierView,
    UpdateSupplierView,
    supplier_detail_view,
    delete_supplier,
    DeleteSupplierView,
    search_supplier,
)

urlpatterns = [
    path('', SupplierView.as_view(), name="suppliers"),
    path('delete/<int:pk>/', DeleteSupplierView.as_view(), name="delete-suppliers"),
    path('new-supplier/', NewSupplierView.as_view(), name="edit-supplier"),
    path('update-supplier/<int:pk>', UpdateSupplierView.as_view(), name="update-supplier"),
    path('delete-supplier/<int:pk>', delete_supplier, name="delete-supplier"),
    path('detail-supplier/<int:pk>', supplier_detail_view, name="detail-supplier"),
    path('search-supplier/', search_supplier, name="search-supplier"),
]

suppliers/models.py
from django.db import models


class SupplierModel(models.Model):
    name = models.CharField(max_length=250)
    address = models.CharField(max_length=250, blank=True, null=True)
    postcode = models.CharField(max_length=10, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    nation = models.CharField(max_length=100, blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    email = models.EmailField(max_length=255, blank=True, null=True)
    btw = models.CharField(max_length=20, blank=True, null=True)
    kvk = models.CharField(max_length=20, blank=True, null=True)
    bankaccountname = models.CharField(max_length=80, blank=True, null=True)
    iban = models.CharField(max_length=34, blank=True, null=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Supplier"
        verbose_name_plural = "Suppliers"


class LoadingAddressModel(models.Model):
    supplier_id = models.ForeignKey(SupplierModel, on_delete=models.CASCADE)
    address = models.CharField(max_length=250)
    postcode = models.CharField(max_length=10)
    city = models.CharField(max_length=100)
    nation = models.CharField(max_length=100)

    def __str__(self):
        return self.address

    class Meta:
        verbose_name = "Loading Address"
        verbose_name_plural = "Loading Addresses"

suppliers/forms.py
from django.forms import ModelForm
from suppliers.models import SupplierModel, LoadingAddressModel
from django.forms import inlineformset_factory


class SupplierForm(ModelForm):
    class Meta:
        model = SupplierModel
        fields = "__all__"


class LoadingAddressForm(ModelForm):
    class Meta:
        model = LoadingAddressModel
        fields = "__all__"


LoadingAddressFormSet = (
    inlineformset_factory(SupplierModel, LoadingAddressModel,
                          form=LoadingAddressForm, extra=1, can_delete=True, can_delete_extra=True))
LoadingAddressFormSetNoExtra = (
    inlineformset_factory(SupplierModel, LoadingAddressModel,
                          form=LoadingAddressForm, extra=0, can_delete=True, can_delete_extra=True))

suppliers/views.py
from django.shortcuts import (
    get_object_or_404,
    reverse,
    redirect
)
from django.views import View
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView
from suppliers.models import SupplierModel, LoadingAddressModel
from suppliers.forms import SupplierForm, LoadingAddressFormSet, LoadingAddressFormSetNoExtra
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib import messages
from django.db.models import Q


class SupplierInLineView(LoginRequiredMixin):
    form_class = SupplierForm
    model = SupplierModel
    template_name = "suppliers/edit-supplier.html"

    def form_valid(self, form):
        context = self.get_context_data()
        named_formsets = context['named_formsets']

        # for formset in named_formsets.values():
        #     print(formset.errors)

        if form.is_valid() and all((x.is_valid() for x in named_formsets.values())):
            self.object = form.save()
            for name, formset in named_formsets.items():
                formset_save_func = getattr(self, 'formset_{0}_valid'.format(name), None)
                if formset_save_func is not None:
                    formset_save_func(formset)
                else:
                    formset.instance = self.object
                    formset.save()
                    print(f"FORMSET_INSTANCE= {formset.instance}")
            return redirect('suppliers')
        else:
            return self.render_to_response(self.get_context_data(form=form))

    def formset_addresses_valid(self, formset):
        loadingaddresses = formset.save(commit=False)
        for obj in formset.deleted_objects:
            obj.delete()
        for address in loadingaddresses:
            address.supplier_id = self.object
            address.save()


class NewSupplierView(SupplierInLineView, CreateView):
    def form_valid(self, form):
        # first save the supplier instance
        self.object = form.save()

        # then create the LoadingAddressFormSet with the instance argument
        address_formset = LoadingAddressFormSet(self.request.POST, instance=self.object, prefix='addresses')
        if not address_formset.is_valid():
            # this will save the addresses with the correct supplier_id
            #     address_formset.save()
            # else:
            # handle formset validation errors
            return self.form_invalid(form)

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['named_formsets'] = {
                "addresses": LoadingAddressFormSet(self.request.POST, prefix='addresses')
            }
            print(f"REQUEST-POST: {self.request.POST}")
        else:
            context['named_formsets'] = {
                "addresses": LoadingAddressFormSet(prefix='addresses')
            }
        return context


class UpdateSupplierView(SupplierInLineView, UpdateView):
    def get_context_data(self, **kwargs):
        context = super(UpdateSupplierView, self).get_context_data(**kwargs)
        context['supplier'] = self.object
        if self.request.method == 'POST':
            context['named_formsets'] = {
                "addresses": LoadingAddressFormSetNoExtra(self.request.POST, instance=self.object, prefix='addresses')
            }
        else:
            context['named_formsets'] = {
                "addresses": LoadingAddressFormSetNoExtra(instance=self.object, prefix='addresses')
            }
        return context


class SupplierView(LoginRequiredMixin, ListView):
    model = SupplierModel
    template_name = "suppliers/suppliers.html"
    context_object_name = "suppliers"


@login_required
def delete_supplier(request, pk):
    try:
        supplier = SupplierModel.objects.get(id=pk)
    except SupplierModel.DoesNotExist:
        messages.success(
            request, 'Object does not exist'
        )

    return redirect('edit-supplier', pk=supplier.supplier_id.id)


class DeleteSupplierView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        supplier_id = self.kwargs['pk']
        supplier = get_object_or_404(SupplierModel, pk=supplier_id)
        supplier.delete()
        return HttpResponseRedirect(reverse('suppliers'))


@login_required()
def supplier_detail_view(request, pk):
    supplier = get_object_or_404(SupplierModel, id=pk)
    loadingaddresses = LoadingAddressModel.objects.filter(supplier_id=supplier)

    # Manually constructing the list of dictionaries for loading addresses
    loading_addresses_data = [
        {
            "address": address.address,
            "postcode": address.postcode,
            "city": address.city,
            "nation": address.nation,
        }
        for address in loadingaddresses
    ]

    supplier_data = {
        "name": supplier.name,
        "address": supplier.address,
        "postcode": supplier.postcode,
        "city": supplier.city,
        "nation": supplier.nation,
        "phone": supplier.phone,
        "email": supplier.email,
        "kvk": supplier.kvk,
        "btw": supplier.btw,
        "bankaccountname": supplier.bankaccountname,
        "iban": supplier.iban,
        "is_active": supplier.is_active
        # If there are more fields, continue listing them here
    }

    context = {
        "supplier": supplier_data,
        "loadingaddresses": loading_addresses_data,
    }

    # return render(request, "suppliers/supplier-detail.html", context=context)
    return JsonResponse(context)


@login_required
def search_supplier(request):
    query = request.GET.get('q', '')
    if query:
        suppliers = SupplierModel.objects.filter(
            Q(name__icontains=query) |
            Q(city__icontains=query) |
            Q(nation__icontains=query)
        ).values('id', 'name', 'address', 'postcode', 'city', 'nation', 'phone', 'email', 'btw', 'kvk',
                 'bankaccountname', 'iban')
    else:
        suppliers = SupplierModel.objects.all().values('id', 'name', 'address', 'postcode', 'city', 'nation', 'phone',
                                                       'email', 'btw', 'kvk', 'bankaccountname', 'iban', 'is_active')

    suppliers_list = list(suppliers)  # Convert QuerySet to list for JSON serialization
    return JsonResponse({'suppliers': suppliers_list, 'count': len(suppliers_list)})

suppliers/templates/suppliers/suppliers.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Suppliers {% endblock title %}
{% block custom_script %}
    <script src="{% static 'js/suppliers/suppliers.js' %}"></script>
{% endblock custom_script %}
{% block page_title %}
    Suppliers
{% endblock page_title %}
{% block content %}
    <div class="container-fluid bg-light-subtle p-2 border-0">
        <div class="row">
            <div class="col-xl-1 col-md-7 mt-2 text-secondary fw-bold small text-end">
                Search:
            </div>
            <div class="col-xl-11 col-md-7 mb-4">
                <input type="text" id="searchSupplier" class="form-control border-secondary" placeholder="Search by name, city or nation...">
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-xl-12 col-md-12 mb-4">
                <div class="card border-0 bg-success-subtle py-2">
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between bg-success">
                        <div class="m-0 fw-bold text-light fs-3">Suppliers</div>
                        <div class="dropdown no-arrow">
                            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuSupplier"  data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="text-decoration: none; color: white;">
                                <i class="bi bi-three-dots-vertical text-secondary-400 fs-3"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuSupplier">
                                <div class="dropdown-header fw-bold border-bottom bg-dark-subtle mb-1 fs-5 text-dark"><i class="bi bi-gear-fill"></i> Action</div>
                                <a class="dropdown-item item-dropdown-font fs-6" href="{% url 'edit-supplier' %}">Add Supplier</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            {% if suppliers %}
                                <table class="table table-striped table-sm">
                                    <thead>
                                        <tr class="table-dark">
                                            <th scope="col">Name</th>
                                            <th scope="col" class="text-center">Address</th>
                                            <th scope="col" class="text-center">Email</th>
                                            <th scope="col" class="text-center">Telephone</th>
                                            <th scope="col" class="text-center">KvK</th>
                                            <th scope="col" class="text-center">BTW</th>
                                            <th scope="col" class="text-center">Bank Details</th>
                                            <th scope="col" class="text-center">Loading Addresses</th>
                                            <th scope="col" class="text-center">Active</th>
                                            <th scope="col" class="text-center">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody id="suppliersTableBody">
                                        {% for supplier in suppliers %}
                                            <tr>
                                                <td class="align-middle">{{ supplier.name }}</td>
                                                <td class="align-middle text-center">
                                                    <a href="https://maps.google.com/?q={{ supplier.address }}, {{ supplier.postcode }} {{ supplier.city }} - {{ supplier.nation }}" class="table_link" target="_blank" title="Go to the Location">
                                                         {{ supplier.address }}, {{ supplier.postcode }} {{ supplier.city }} - {{ supplier.nation }}
                                                     </a>
                                                </td>
                                                <td class="align-middle text-center">
                                                    <a href="mailto:{{ supplier.email }}" class="table_link">
                                                        {{ supplier.email }}
                                                    </a>
                                                </td>
                                                <td class="align-middle text-center">{{ supplier.phone }}</td>
                                                <td class="align-middle text-center">{{ supplier.kvk }}</td>
                                                <td class="align-middle text-center">{{ supplier.btw }}</td>
                                                <td class="align-middle text-center">{{ supplier.bankaccountname }}: {{ supplier.iban }}</td>
                                                <td class="align-middle text-center">{{ supplier.loadingaddressmodel_set.count }}</td>
                                                <td class="align-middle text-center">
                                                    {% if supplier.is_active %}
                                                        <span class="text-success">True</span>
                                                    {% else %}
                                                        <span class="text-danger">False</span>
                                                    {% endif %}
                                                </td>
                                                <td class="align-middle text-center">
                                                    <span>
                                                        <a href="{% url 'update-supplier' supplier.id %}" style="text-decoration: none;">
                                                            <i class="bi bi-pencil-square fw-bold link-success fs-4" title="Edit"></i>
                                                        </a>
                                                    </span>
                                                    <span>
                                                        <a class="delete-button" data-company-id="{{ supplier.pk }}" title="Delete">
                                                            <i class="bi bi-trash fw-bold link-danger fs-4" title="Delete"></i>
                                                        </a>
                                                    </span>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            {% else %}
                                <div class="text-center text-secondary fw-bolder fs-2">
                                    No Suppliers registered in the database. <i class="bi bi-emoji-frown-fill"></i>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block custom_bottom_script %}
    <script src="{% static 'js/suppliers/searchSupplier.js' %}"></script>
{% endblock custom_bottom_script %}